spring:
  datasource:
    url: jdbc:mysql://sh-cdb-ow7uekkj.sql.tencentcdb.com:63183/recycle?useUnicode=true&useSSL=false
    username: root
    password: recycle123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4

  #jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  #重定向转发配置
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**

  # 这个开发配置为false，避免改了模板还要重启服务器
  thymeleaf:
    cache: false
  # 这个是配置模板路径的，默认就是templates，可不用配置
    prefix: classpath:/templates/
  # 这个可以不配置，检查模板位置
    check-template-location: true
  # 下面3个不做解释了，可以不配置
    suffix: .html
    encoding: UTF-8

#日志配置
logging:
  level:
    org.springframework.web: DEBUG
debug: true


